package ebi.ws.client;

import javax.xml.ws.WebFault;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 * 
 */
@WebFault(name = "QueryException", targetNamespace = "http://webservice.cdb.ebi.ac.uk/")
public class QueryException_Exception extends Exception {

	private static final long serialVersionUID = 1L;
	
	/**
	 * Java type that goes as soapenv:Fault detail element.
	 * 
	 */
	private QueryException faultInfo;

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 */
	public QueryException_Exception(String message, QueryException faultInfo) {
		super(message);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 * @param cause
	 */
	public QueryException_Exception(String message, QueryException faultInfo, Throwable cause) {
		super(message, cause);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @return returns fault bean: ebi.ws.client.QueryException
	 */
	public QueryException getFaultInfo() {
		return faultInfo;
	}

}
