
package ebi.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSCitationImpl", targetNamespace = "http://webservice.cdb.ebi.ac.uk/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSCitationImpl {


    /**
     * 
     * @param queryString
     * @param email
     * @param synonym
     * @param resultType
     * @param offSet
     * @param dataSet
     * @return
     *     returns ebi.ws.client.ResponseWrapper
     * @throws QueryException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchPublications", targetNamespace = "http://webservice.cdb.ebi.ac.uk/", className = "ebi.ws.client.SearchPublications")
    @javax.xml.ws.ResponseWrapper(localName = "searchPublicationsResponse", targetNamespace = "http://webservice.cdb.ebi.ac.uk/", className = "ebi.ws.client.SearchPublicationsResponse")
    public ebi.ws.client.ResponseWrapper searchPublications(
        @WebParam(name = "queryString", targetNamespace = "")
        String queryString,
        @WebParam(name = "dataSet", targetNamespace = "")
        String dataSet,
        @WebParam(name = "resultType", targetNamespace = "")
        String resultType,
        @WebParam(name = "offSet", targetNamespace = "")
        Integer offSet,
        @WebParam(name = "synonym", targetNamespace = "")
        Boolean synonym,
        @WebParam(name = "email", targetNamespace = "")
        String email)
        throws QueryException_Exception
    ;

    /**
     * 
     * @param queryString
     * @param profileType
     * @param email
     * @param synonym
     * @param dataSet
     * @return
     *     returns ebi.ws.client.ResponseWrapper
     * @throws QueryException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "profilePublications", targetNamespace = "http://webservice.cdb.ebi.ac.uk/", className = "ebi.ws.client.ProfilePublications")
    @javax.xml.ws.ResponseWrapper(localName = "profilePublicationsResponse", targetNamespace = "http://webservice.cdb.ebi.ac.uk/", className = "ebi.ws.client.ProfilePublicationsResponse")
    public ebi.ws.client.ResponseWrapper profilePublications(
        @WebParam(name = "queryString", targetNamespace = "")
        String queryString,
        @WebParam(name = "dataSet", targetNamespace = "")
        String dataSet,
        @WebParam(name = "profileType", targetNamespace = "")
        String profileType,
        @WebParam(name = "synonym", targetNamespace = "")
        Boolean synonym,
        @WebParam(name = "email", targetNamespace = "")
        String email)
        throws QueryException_Exception
    ;

    /**
     * 
     * @param id
     * @param source
     * @param email
     * @param offSet
     * @return
     *     returns ebi.ws.client.ResponseWrapper
     * @throws QueryException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCitations", targetNamespace = "http://webservice.cdb.ebi.ac.uk/", className = "ebi.ws.client.GetCitations")
    @javax.xml.ws.ResponseWrapper(localName = "getCitationsResponse", targetNamespace = "http://webservice.cdb.ebi.ac.uk/", className = "ebi.ws.client.GetCitationsResponse")
    public ebi.ws.client.ResponseWrapper getCitations(
        @WebParam(name = "id", targetNamespace = "")
        String id,
        @WebParam(name = "source", targetNamespace = "")
        String source,
        @WebParam(name = "offSet", targetNamespace = "")
        Integer offSet,
        @WebParam(name = "email", targetNamespace = "")
        String email)
        throws QueryException_Exception
    ;

    /**
     * 
     * @param id
     * @param source
     * @param email
     * @param offSet
     * @return
     *     returns ebi.ws.client.ResponseWrapper
     * @throws QueryException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getReferences", targetNamespace = "http://webservice.cdb.ebi.ac.uk/", className = "ebi.ws.client.GetReferences")
    @javax.xml.ws.ResponseWrapper(localName = "getReferencesResponse", targetNamespace = "http://webservice.cdb.ebi.ac.uk/", className = "ebi.ws.client.GetReferencesResponse")
    public ebi.ws.client.ResponseWrapper getReferences(
        @WebParam(name = "id", targetNamespace = "")
        String id,
        @WebParam(name = "source", targetNamespace = "")
        String source,
        @WebParam(name = "offSet", targetNamespace = "")
        Integer offSet,
        @WebParam(name = "email", targetNamespace = "")
        String email)
        throws QueryException_Exception
    ;

    /**
     * 
     * @param id
     * @param semanticType
     * @param source
     * @param email
     * @param offSet
     * @return
     *     returns ebi.ws.client.ResponseWrapper
     * @throws QueryException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTextMinedTerms", targetNamespace = "http://webservice.cdb.ebi.ac.uk/", className = "ebi.ws.client.GetTextMinedTerms")
    @javax.xml.ws.ResponseWrapper(localName = "getTextMinedTermsResponse", targetNamespace = "http://webservice.cdb.ebi.ac.uk/", className = "ebi.ws.client.GetTextMinedTermsResponse")
    public ebi.ws.client.ResponseWrapper getTextMinedTerms(
        @WebParam(name = "id", targetNamespace = "")
        String id,
        @WebParam(name = "source", targetNamespace = "")
        String source,
        @WebParam(name = "semanticType", targetNamespace = "")
        String semanticType,
        @WebParam(name = "offSet", targetNamespace = "")
        Integer offSet,
        @WebParam(name = "email", targetNamespace = "")
        String email)
        throws QueryException_Exception
    ;

    /**
     * 
     * @param id
     * @param source
     * @param email
     * @param offSet
     * @param database
     * @return
     *     returns ebi.ws.client.ResponseWrapper
     * @throws QueryException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDatabaseLinks", targetNamespace = "http://webservice.cdb.ebi.ac.uk/", className = "ebi.ws.client.GetDatabaseLinks")
    @javax.xml.ws.ResponseWrapper(localName = "getDatabaseLinksResponse", targetNamespace = "http://webservice.cdb.ebi.ac.uk/", className = "ebi.ws.client.GetDatabaseLinksResponse")
    public ebi.ws.client.ResponseWrapper getDatabaseLinks(
        @WebParam(name = "id", targetNamespace = "")
        String id,
        @WebParam(name = "source", targetNamespace = "")
        String source,
        @WebParam(name = "database", targetNamespace = "")
        String database,
        @WebParam(name = "offSet", targetNamespace = "")
        Integer offSet,
        @WebParam(name = "email", targetNamespace = "")
        String email)
        throws QueryException_Exception
    ;

    /**
     * 
     * @param id
     * @param source
     * @param email
     * @return
     *     returns ebi.ws.client.Result
     * @throws QueryException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSupplementaryFiles", targetNamespace = "http://webservice.cdb.ebi.ac.uk/", className = "ebi.ws.client.GetSupplementaryFiles")
    @javax.xml.ws.ResponseWrapper(localName = "getSupplementaryFilesResponse", targetNamespace = "http://webservice.cdb.ebi.ac.uk/", className = "ebi.ws.client.GetSupplementaryFilesResponse")
    public Result getSupplementaryFiles(
        @WebParam(name = "id", targetNamespace = "")
        String id,
        @WebParam(name = "source", targetNamespace = "")
        String source,
        @WebParam(name = "email", targetNamespace = "")
        String email)
        throws QueryException_Exception
    ;

    /**
     * 
     * @param id
     * @param source
     * @param email
     * @return
     *     returns ebi.ws.client.Result
     * @throws QueryException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFulltextXML", targetNamespace = "http://webservice.cdb.ebi.ac.uk/", className = "ebi.ws.client.GetFulltextXML")
    @javax.xml.ws.ResponseWrapper(localName = "getFulltextXMLResponse", targetNamespace = "http://webservice.cdb.ebi.ac.uk/", className = "ebi.ws.client.GetFulltextXMLResponse")
    public Result getFulltextXML(
        @WebParam(name = "id", targetNamespace = "")
        String id,
        @WebParam(name = "source", targetNamespace = "")
        String source,
        @WebParam(name = "email", targetNamespace = "")
        String email)
        throws QueryException_Exception
    ;

    /**
     * 
     * @param email
     * @return
     *     returns ebi.ws.client.ResponseWrapper
     * @throws QueryException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listSearchFields", targetNamespace = "http://webservice.cdb.ebi.ac.uk/", className = "ebi.ws.client.ListSearchFields")
    @javax.xml.ws.ResponseWrapper(localName = "listSearchFieldsResponse", targetNamespace = "http://webservice.cdb.ebi.ac.uk/", className = "ebi.ws.client.ListSearchFieldsResponse")
    public ebi.ws.client.ResponseWrapper listSearchFields(
        @WebParam(name = "email", targetNamespace = "")
        String email)
        throws QueryException_Exception
    ;

    /**
     * 
     * @param id
     * @param source
     * @param email
     * @param providerId
     * @param offSet
     * @return
     *     returns ebi.ws.client.ResponseWrapper
     * @throws QueryException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLabsLinks", targetNamespace = "http://webservice.cdb.ebi.ac.uk/", className = "ebi.ws.client.GetLabsLinks")
    @javax.xml.ws.ResponseWrapper(localName = "getLabsLinksResponse", targetNamespace = "http://webservice.cdb.ebi.ac.uk/", className = "ebi.ws.client.GetLabsLinksResponse")
    public ebi.ws.client.ResponseWrapper getLabsLinks(
        @WebParam(name = "id", targetNamespace = "")
        String id,
        @WebParam(name = "source", targetNamespace = "")
        String source,
        @WebParam(name = "providerId", targetNamespace = "")
        String providerId,
        @WebParam(name = "offSet", targetNamespace = "")
        Integer offSet,
        @WebParam(name = "email", targetNamespace = "")
        String email)
        throws QueryException_Exception
    ;

}
